import type { PropertyInput } from "./properties";

// Demo ilan verisi. Görseller repoya dahil edilen statik dosyaları işaret eder
// (public/uploads/seed-*.jpg). Hem CLI seed (scripts/seed.ts) hem de DB boşsa
// çalışan otomatik seed (lib/db.ts) bu listeyi kullanır — tek kaynak.
const img = (key: string) => `/uploads/seed-${key}.jpg`;

export const SEED_LISTINGS: PropertyInput[] = [
  {
    title: "Caferağa'da Denize Yakın Bakımlı 3+1 Daire",
    category: "konut",
    status: "satilik",
    price: 8750000,
    currency: "TRY",
    city: "İstanbul",
    district: "Kadıköy",
    neighborhood: "Caferağa",
    grossArea: 145,
    netArea: 125,
    rooms: "3+1",
    bathrooms: 2,
    buildingAge: "5-10",
    floor: "4. Kat",
    totalFloors: 7,
    heating: "Kombi (Doğalgaz)",
    furnished: 0,
    inSite: 0,
    zoning: null,
    blockParcel: null,
    description:
      "Kadıköy Caferağa'nın en sakin sokaklarından birinde, denize ve Moda'ya yürüme mesafesinde, bakımlı bir binada satılık 3+1 daire. Geniş salon, ebeveyn banyolu yatak odası, ankastre mutfak ve cephesi açık ferah balkon. Metro, vapur ve Bağdat Caddesi'ne kolay ulaşım. Yatırım ve oturum için ideal.",
    features: ["Asansör", "Balkon", "Doğalgaz", "Ankastre Mutfak", "Ebeveyn Banyosu", "Çelik Kapı", "Görüntülü Diafon", "Krediye Uygun"],
    images: [img("salon1"), img("salon2"), img("mutfak"), img("yatak"), img("banyo")],
    coverImage: null,
    latitude: 40.9885,
    longitude: 29.0277,
    reference: null,
    published: 1,
    featured: 1,
  },
  {
    title: "Levent'te Yüksek Katlı Lüks 2+1 Rezidans Dairesi",
    category: "konut",
    status: "satilik",
    price: 14250000,
    currency: "TRY",
    city: "İstanbul",
    district: "Beşiktaş",
    neighborhood: "Levent",
    grossArea: 120,
    netArea: 98,
    rooms: "2+1",
    bathrooms: 1,
    buildingAge: "0 (Sıfır)",
    floor: "21. Kat",
    totalFloors: 32,
    heating: "Merkezi (Pay Ölçer)",
    furnished: 1,
    inSite: 1,
    zoning: null,
    blockParcel: null,
    description:
      "Levent'in merkezinde, 7/24 güvenlikli prestijli bir rezidansta, şehir manzaralı eşyalı 2+1 daire. Yüzme havuzu, fitness, concierge ve kapalı otopark gibi sosyal olanaklara sahip. İş merkezlerine ve metroya yürüme mesafesinde; üst düzey yatırım fırsatı.",
    features: ["Asansör", "Kapalı Otopark", "Güvenlik", "Yüzme Havuzu", "Spor Salonu", "Eşyalı", "Site İçinde", "Isı Yalıtımı"],
    images: [img("bina"), img("salon3"), img("salon1"), img("yatak")],
    coverImage: null,
    latitude: 41.0808,
    longitude: 29.0101,
    reference: null,
    published: 1,
    featured: 1,
  },
  {
    title: "Çankaya'da Geniş ve Aydınlık 4+1 Kiralık Daire",
    category: "konut",
    status: "kiralik",
    price: 42000,
    currency: "TRY",
    city: "Ankara",
    district: "Çankaya",
    neighborhood: "Çukurambar",
    grossArea: 190,
    netArea: 165,
    rooms: "4+1",
    bathrooms: 2,
    buildingAge: "1",
    floor: "6. Kat",
    totalFloors: 12,
    heating: "Yerden Isıtma",
    furnished: 0,
    inSite: 1,
    zoning: null,
    blockParcel: null,
    description:
      "Çukurambar'ın yeni nesil sitelerinden birinde, aileler için ideal geniş 4+1 kiralık daire. Yerden ısıtma, akıllı ev altyapısı, kapalı otopark ve site içi sosyal donatılar. AVM, okul ve metroya yakın konum.",
    features: ["Asansör", "Kapalı Otopark", "Güvenlik", "Site İçinde", "Çocuk Oyun Alanı", "Ankastre Mutfak", "Görüntülü Diafon"],
    images: [img("salon2"), img("salon3"), img("mutfak")],
    coverImage: null,
    latitude: 39.9035,
    longitude: 32.8086,
    reference: null,
    published: 1,
    featured: 0,
  },
  {
    title: "Çeşme'de Konut İmarlı Yatırımlık Arsa",
    category: "arsa",
    status: "satilik",
    price: 12500000,
    currency: "TRY",
    city: "İzmir",
    district: "Çeşme",
    neighborhood: "Alaçatı",
    grossArea: 850,
    netArea: null,
    rooms: null,
    bathrooms: null,
    buildingAge: null,
    floor: null,
    totalFloors: null,
    heating: null,
    furnished: 0,
    inSite: 0,
    zoning: "Konut İmarlı",
    blockParcel: "1284 / 17",
    description:
      "Alaçatı'ya yakın, konut imarlı, köşe başı yatırımlık arsa. %30 emsal, 2 kat imar hakkı. Denize ulaşım kolay, çevresi villalarla gelişmekte olan bir bölgede. Tapusu temiz, ifrazlı ve hemen yapılaşmaya uygun.",
    features: ["Krediye Uygun", "Doğa Manzarası"],
    images: [img("arsa1"), img("arsa2")],
    coverImage: null,
    latitude: 38.2795,
    longitude: 26.3705,
    reference: null,
    published: 1,
    featured: 1,
  },
  {
    title: "Şişli Merkezde Cephe Kiralık Ofis Katı",
    category: "isyeri",
    status: "kiralik",
    price: 95000,
    currency: "TRY",
    city: "İstanbul",
    district: "Şişli",
    neighborhood: "Merkez",
    grossArea: 220,
    netArea: 195,
    rooms: null,
    bathrooms: 2,
    buildingAge: "5-10",
    floor: "3. Kat",
    totalFloors: 9,
    heating: "Merkezi (Doğalgaz)",
    furnished: 0,
    inSite: 0,
    zoning: null,
    blockParcel: null,
    description:
      "Şişli'nin en işlek aksında, metroya 2 dakika mesafede, açık ofis düzenine uygun cephe ofis katı. Yüksek tavan, bol ışık, 2 wc ve çay ocağı. Plaza güvenliği ve otopark imkânı. Kurumsal firmalar için prestijli konum.",
    features: ["Asansör", "Kapalı Otopark", "Güvenlik", "Doğalgaz", "Isı Yalıtımı"],
    images: [img("ofis1"), img("ofis2")],
    coverImage: null,
    latitude: 41.0602,
    longitude: 28.9877,
    reference: null,
    published: 1,
    featured: 0,
  },
  {
    title: "Nilüfer'de Cadde Üzeri Satılık Dükkan",
    category: "ticari",
    status: "satilik",
    price: 6800000,
    currency: "TRY",
    city: "Bursa",
    district: "Nilüfer",
    neighborhood: "Görükle",
    grossArea: 110,
    netArea: 95,
    rooms: null,
    bathrooms: 1,
    buildingAge: "11-15",
    floor: "Zemin Kat",
    totalFloors: 5,
    heating: "Klima",
    furnished: 0,
    inSite: 0,
    zoning: null,
    blockParcel: null,
    description:
      "Görükle'de yoğun yaya trafiğine sahip cadde üzerinde, geniş vitrinli zemin kat dükkan. Üniversiteye yakın, kira getirisi yüksek lokasyon. Her türlü ticari faaliyete uygun, devren değil mülk satışı.",
    features: ["Doğalgaz", "Krediye Uygun"],
    images: [img("dukkan")],
    coverImage: null,
    latitude: 40.2275,
    longitude: 28.8472,
    reference: null,
    published: 1,
    featured: 0,
  },
  {
    title: "Bodrum Yalıkavak'ta Deniz Manzaralı Müstakil Villa",
    category: "konut",
    status: "satilik",
    price: 32000000,
    currency: "TRY",
    city: "Muğla",
    district: "Bodrum",
    neighborhood: "Yalıkavak",
    grossArea: 320,
    netArea: 280,
    rooms: "5+2",
    bathrooms: 4,
    buildingAge: "0 (Sıfır)",
    floor: "Müstakil",
    totalFloors: 3,
    heating: "Yerden Isıtma",
    furnished: 1,
    inSite: 1,
    zoning: null,
    blockParcel: null,
    description:
      "Yalıkavak'ta kesintisiz deniz manzaralı, özel havuzlu, akıllı ev sistemli lüks müstakil villa. Geniş bahçe, infinity havuz, kapalı garaj ve eşyalı teslim. Marina ve plajlara dakikalar mesafesinde; yıllık kira getirisi ve değer artışı yüksek.",
    features: ["Yüzme Havuzu", "Bahçe", "Teras", "Deniz Manzarası", "Eşyalı", "Güvenlik", "Site İçinde", "Çelik Kapı", "Isı Yalıtımı"],
    images: [img("villaDis"), img("villaDis2"), img("deniz"), img("salon3"), img("yatak")],
    coverImage: null,
    latitude: 37.1075,
    longitude: 27.2925,
    reference: null,
    published: 1,
    featured: 1,
  },
];
